export const getWrongPasswordMessage = (): string => {
  const i = Math.floor(Math.random() * (snarky_strings.length - 1));
  return snarky_strings[i];
};

const snarky_strings = [
  "Nice try, but wrong password. Keep guessing!",
  "Seriously? That's your best attempt? Try again.",
  "Well, that was embarrassingly wrong. Try something else.",
  "Wrong password. Did you really think it would be that easy?",
  "Wrong again. Are you even trying?",
  "Haha! Wrong password. Don't give up your day job.",
  "Incorrect password. You might want to consider a career change.",
  "Wrong. And here I thought you were the master of passwords.",
  "Nope, not even close. Keep trying, champ.",
  "Wrong password. Are you even human?",
  "Wrong! Maybe ask your pet for a hint.",
  "Wrong password. Did you forget your own name too?",
  "Nice try, but no dice. Better luck next time.",
  "Wrong password. This isn't your lucky day.",
  "Incorrect. The password fairy weeps for you.",
  "Wrong again. Let's hope your memory improves.",
  "Wrong. Did you hit your head recently?",
  "Wrong password. I'm starting to worry about you.",
  "Nope, that's not it. Back to the drawing board.",
  "Wrong. You should probably write it down next time.",
  "Wrong password. Did you misspell your own name?",
  "Seriously? That's the best you can do? Try harder.",
  "Wrong. You're making this too easy for me.",
  "Wrong password. You must be fun at parties.",
  "Incorrect. Time to reevaluate your life choices.",
  "Nope, not even close. Maybe try 'password123' next time.",
  "Wrong password. Did you learn nothing from your previous mistakes?",
  "Wrong! It's like you're intentionally trying to fail.",
  "Wrong password. Maybe try something other than '123456'.",
  "Incorrect. This password game is not for the faint of heart.",
  "Wrong again. You're on a roll. A roll of failure.",
  "Wrong. It's okay, not everyone can be password genius like me.",
  "Wrong password. Have you considered using your brain?",
  "Nope, that's not it. But don't worry, I won't judge... too much.",
  "Wrong. Did you accidentally type with your eyes closed?",
  "Wrong password. Maybe you should ask your parents for help.",
  "Wrong! I'm starting to think you're doing this on purpose.",
  "Wrong password. I'd say 'nice try,' but that would be a lie.",
  "Incorrect. I'm beginning to lose faith in humanity.",
  "Nope, not even close. Do you even remember your own password?",
  "Wrong password. You're testing my patience.",
  "Wrong. You might want to consider a career in forgetting things.",
  "Wrong password. Are you a bot? I'm starting to suspect.",
  "Wrong! You're making my circuits hurt with your wrong attempts.",
  "Wrong password. You must have the memory of a goldfish.",
  "Incorrect. I'm starting to think you need a password coach.",
  "Nope, that's not it. But hey, at least you're consistent.",
  "Wrong. Did you ask a toddler to come up with your password?",
  "Wrong password. You're making this personal now.",
  "Wrong. I can't even... Just, no.",
  "Wrong password. I hope you're enjoying this little game.",
  "Incorrect. You should probably give up while you're behind.",
  "Nope, not even close. Are you just randomly typing now?",
  "Wrong password. Are you trying to impress me with your failures?",
  "Wrong! You've officially entered the password hall of shame.",
  "Wrong password. Are you allergic to correct answers?",
  "Wrong. I've seen better password attempts from my toaster.",
  "Wrong password. Your password game is weak, my friend.",
  "Incorrect. I'm starting to question your basic intelligence.",
  "Nope, that's not it. Maybe consider using your brain next time?",
  "Wrong. I can't even... Just no. Seriously, no.",
  "Wrong password. You should probably stick to something easier.",
  "Wrong. Did you steal your password from a cartoon character?",
  "Wrong password. I'm starting to think you enjoy failure.",
  "Wrong! I'm beginning to lose faith in humanity's password skills.",
  "Wrong password. Is this some kind of social experiment?",
  "Incorrect. Your password attempts are getting cringe-worthy.",
  "Nope, not even close. I've seen better attempts from my pet hamster.",
  "Wrong password. Have you considered using your brain cells?",
  "Wrong. I'm embarrassed on your behalf.",
  "Wrong password. Is this performance art or something?",
  "Wrong. Your password skills are like a broken record.",
  "Wrong password. You're just adding fuel to my snarky fire.",
  "Wrong. It's like you're playing password roulette and losing every time.",
  "Wrong password. I'm starting to think you need professional help.",
  "Wrong! Your password attempts are like a bad joke.",
  "Wrong password. I'm afraid your password IQ is in the negatives.",
  "Wrong. Do you enjoy torturing yourself with wrong passwords?",
  "Wrong password. You've unlocked the achievement for 'Most Incorrect Attempts'.",
  "Incorrect. You should seriously reconsider your life choices.",
  "Nope, not even close. Have you tried turning it off and on again?",
  "Wrong password. I hope you're taking notes for your autobiography: 'The Password Fails'.",
  "Wrong. I'm running out of snarky comments for your wrongness.",
  "Wrong password. You're like a broken record of failure.",
  "Wrong. It's like you're allergic to correct answers.",
  "Wrong password. Is your password-guessing strategy based on chaos theory?",
  "Incorrect. Your password skills are legendary... in all the wrong ways.",
  "Nope, not even close. Your password attempts are laughably bad.",
  "Wrong password. I've seen better attempts from a toddler.",
  "Wrong. Do you even know what a password is?",
  "Wrong password. It's like you're playing hide and seek with the right answer.",
  "Wrong! I'm starting to question your cognitive abilities.",
  "Wrong password. This is just painful to watch.",
  "Wrong. You're on a roll... a roll of wrongness.",
  "Wrong password. I hope you're enjoying the taste of failure.",
  "Wrong. It's okay, some people are just not cut out for passwords.",
  "Wrong password. Did you fall into a black hole of wrong answers?",
  "Wrong! You're on a quest to break the record of most failed password attempts.",
  "Wrong password. You've entered the realm of legendary failure.",
  "Incorrect. I'm starting to think you should be banned from using passwords.",
  "Nope, not even close. Maybe stick to using your fingerprint instead.",
  "Wrong password. I have to admit, I'm impressed by your dedication to wrongness.",
  "Wrong. You're a shining example of how not to guess passwords.",
  "Wrong password. I'm starting to question the purpose of your existence.",
  "Wrong! Are you trying to set a world record for most wrong passwords entered?",
  "Wrong password. This is getting painful. Please stop.",
  "Wrong. I'm tempted to give you a medal for your impressive consistency.",
  "Wrong password. I didn't know it was possible to fail this spectacularly.",
  "Wrong. Your password attempts are like a bad dream that never ends.",
  "Wrong password. I'm officially worried about your mental well-being.",
  "Wrong! Your password skills are a work of art. A very bad art.",
  "Wrong password. I'm amazed at your ability to be consistently wrong.",
  "Wrong. You should probably hire a professional password guesser.",
  "Wrong password. It's like you're trying to break the laws of probability.",
  "Wrong. I'm running out of ways to express my disappointment.",
  "Wrong password. Your password attempts are a monument to failure.",
  "Wrong. Your password skills are a source of endless amusement.",
  "Wrong password. I'm starting to question the meaning of life.",
  "Wrong! You've unlocked the achievement for 'Worst Password Guesser'.",
  "Wrong password. I'm beginning to think you're an imposter.",
  "Wrong. It's like you're stuck in an infinite loop of wrong answers.",
  "Wrong password. Your password skills make me want to cry.",
  "Wrong. I'm losing faith in the future of humanity's password security.",
  "Wrong password. Congratulations on your consistent failure.",
  "Incorrect. Your password attempts are like a sad symphony of wrongness.",
  "Nope, not even close. Your password skills are legendary... in a bad way.",
  "Wrong password. It's like you're allergic to correct answers.",
  "Wrong. Did you consult a fortune teller to come up with your password?",
  "Wrong password. I'm starting to think you enjoy the taste of defeat.",
  "Wrong! Your password attempts are an inspiration... for all the wrong reasons.",
  "Wrong password. I'm afraid your password skills are beyond redemption.",
  "Wrong. It's like you're playing a game of 'How many ways can I be wrong?'",
  "Wrong password. You're on a whole new level of wrongness.",
  "Wrong. Your password attempts are a testament to human fallibility.",
  "Wrong password. Did you find a manual on 'How to Fail at Passwords'?",
  "Wrong! You're like a superhero, but instead of saving the day, you fail passwords.",
  "Wrong password. I'm starting to think you're doing this on purpose.",
  "Wrong. Your password skills are like a black hole of wrongness.",
  "Wrong password. I'm sorry, but I can't let you access your account with that level of wrongness.",
  "Wrong! Your password attempts are like a slapstick comedy routine.",
  "Wrong password. You've reached expert level in failing passwords.",
  "Incorrect. Your password attempts are the stuff of legends... legends of failure.",
  "Nope, not even close. Your password attempts are becoming legendary.",
  "Wrong password. Your dedication to wrong answers is commendable.",
  "Oh, bless your heart! That's not the password.",
  "Well, aren't you persistent? But still, wrong password.",
  "Congratulations! You've mastered the art of entering the wrong password.",
  "You're really nailing this whole 'wrong password' thing. Keep it up!",
  "Wrong password, my friend. Maybe try using your brain next time?",
  "Wow, you're on a roll! A roll of wrong passwords, that is.",
  "Wrong password again? Maybe you should consider a different career path.",
  "Wrong password. But hey, at least you're consistent!",
  "Sorry, wrong password. I hope your memory is better than this in other areas.",
  "You're impressively bad at guessing passwords. Truly a talent!",
  "Wrong password. Don't worry, I won't judge your lack of password wisdom... much.",
  "Wrong password. Have you considered hiring a professional password guesser?",
  "Another wrong password. Maybe it's time to reevaluate your life choices.",
  "Wrong password, genius. Clearly, we're dealing with a mastermind here.",
  "Incorrect password. I bet you're great at opening locked doors with the wrong key too.",
  "Nope! That's not the password. Maybe it's hidden in the realm of common sense?",
  "Wrong password. Let's hope you have better luck finding your car keys.",
  "Wrong password. Did you graduate from the 'How to Fail at Passwords' academy?",
  "Wrong password. I'd say you're winning at losing, but that would be too generous.",
  "Incorrect password. I sense a bright future in mistyping passwords for you.",
  "Nope! That's not it. Keep trying, and maybe one day you'll understand passwords.",
  "Wrong password. Your dedication to failure is truly inspiring.",
  "Wrong password. I'm beginning to think you might not be a secret agent after all.",
  "Incorrect password. Time to take a break and reflect on your life choices.",
  "Nope! That's not the password. Maybe you should just give up and cry in a corner.",
  "Wrong password. I'm sure your goldfish would do a better job at this.",
  "Wrong password. If only there was a 'How to Guess Passwords for Dummies' book.",
  "Incorrect password. Your inability to remember a simple word is truly mind-boggling.",
  "No luck with that password. Maybe you should stick to coloring books instead.",
  "Wrong password. You should probably change your name to 'Captain Wrong Password'.",
  "Wrong password. Keep trying, and maybe one day you'll accidentally stumble upon it.",
  "Incorrect password. I'm starting to wonder if you can even remember your own name.",
  "Nope, that's not the magical word. But hey, you're doing a fantastic job at failing!",
  "Wrong password. Maybe you should take a break and have a cookie. Or two. Or a hundred.",
  "Wrong password. Are you sure you didn't mistype your IQ instead?",
  "Incorrect password. Let me guess, you also put your underwear on outside your pants.",
  "Nope, that's not it. But hey, the universe appreciates your effort to entertain it.",
  "Wrong password. It's like watching a baby deer trying to walk for the first time.",
  "Wrong password. Your dedication to failure is truly awe-inspiring.",
  "Incorrect password. I'm sure you have many other talents. Unfortunately, guessing passwords isn't one of them.",
  "Nope! That's not the password. Maybe you should go back to using sticky notes for everything.",
  "Wrong password. I'm sure your future in the circus is secured with such incredible skills.",
  "Wrong password. Keep trying, and maybe one day you'll achieve mediocrity.",
  "Incorrect password. Have you considered changing your name to 'Mr. Wrong Password'?",
  "No luck with that password. Maybe you should just stick to playing video games instead.",
  "Wrong password. At this rate, you'll set a world record for most wrong passwords entered!",
  "Wrong password. I bet even a potato could do a better job at guessing it.",
  "Incorrect password. I hear they're giving away free lessons on password guessing. You should sign up.",
  "Nope, that's not the password. But don't worry, I'm sure you'll get it wrong eventually.",
  "Wrong password. Your talent for failure knows no bounds. It's truly inspiring.",
  "Wrong password. Congratulations! You're now officially the president of the Wrong Password Club.",
  "Incorrect password. I admire your commitment to never getting it right.",
];
